### ISSUE TITLE
MacOS window messaging

### ISSUE THREAD

**Issue by cnkeenan** [mmkk-group/mmkkengine#1]
Must be able to process a window close message (or function/delegate) in Cocoa. In that message (function/delegate) set the environment manager execution state to exit to exit the program correctly.

**Comment by cnkeenan** [comment]
A couple of things have changed since this was assigned. We have the ability to close the process now but it does not use the execution state function defined in EnvironmentManager.cpp. I am unsure if there is a way to attach these two functions, but there may be a way to possible create a message that passes to the engine to cease all functions after this function is called?

**Comment by cnkeenan** [comment]
`@implementation AppDelegate : NSObject

// The additional functions here


- (BOOL)applicationShouldTerminateAfterLastWindowClosed:(NSApplication *)sender
{
    
    return YES;
}`


The above function is what handles the system call when a user selects the X button to terminate the window. So it may not directly call the ExecutionState function.

**Comment by JJ-Karambasis** [comment]
You can still call EnvironmentManager::Get()->ExecutionState(EExecutionState::EXIT) in that function that terminates the window process. Unless I'm not thinking of something else. Before you commit the mac changes we should talk about because maybe we need a slight design change in the window structure.

**Comment by cnkeenan** [comment]
@JJ-Karambasis this issue should be closed upon the merging of PR #17 which fixes all of these issues and handles them via the engine functions.

**Comment by cnkeenan** [comment]
@JJ-Karambasis @rayrase @marshy2346 closing this issue as PR #17 was merged successfully
