### ISSUE TITLE
Linux Timer randomly displays a long delay

### ISSUE THREAD

**Issue by rayrase** [mmkk-group/mmkkengine#12]
INFO:   18446744072721.250000ms/f

This occurs every now and then. I believe it will be fixed once the ProcessOSMessages for Linux is reimplemented to not block when there are no events. I am keeping it here just in case.

**Comment by cnkeenan** [comment]
Confirmed that this also does happen on MacOS as well.

**Comment by rayrase** [comment]
Confirmed that this is fixed for Linux in #25 . Waiting on MacOS confirmation.

**Comment by rayrase** [comment]
Fixed.
