### ISSUE TITLE
Linux OpenGL context initialization

### ISSUE THREAD

**Issue by cnkeenan** [mmkk-group/mmkkengine#4]
Initialize OpenGL 3.3 for linux. Make sure to dynamic link to opengl.

**Comment by rayrase** [comment]
#11
I don't think I'm dynamically linking but it works. Need to work with JJ to make sure I'm doing this correctly.

**Comment by rayrase** [comment]
This issue is on hold until Friday.

**Comment by rayrase** [comment]
Completed in #25.
